### ISSUE TITLE
Fantomas Integration

### ISSUE THREAD

**Issue by cannorin** [ionide/Ionide-vim#13]

**Comment by Krzysztof-Cieslak** [comment]
This is handled as part of LSP, shouldn’t you get it for free

**Comment by cannorin** [comment]
That's the point, I must try it out first.

**Comment by cannorin** [comment]
OK, formatting works out of the box through LSP, but we should be able to configure it through settings so some work would be needed

**Comment by cannorin** [comment]
It seems I have to set initializationOptions and LanguageClient-neovim can only specify JSON files to use as the parameter, but `workspace/didChangeConfiguration` can be used to do runtime configuration. I'll address it as a generic configuration support.

**Comment by cannorin** [comment]
Ah https://github.com/fsprojects/fantomas/issues/354

**Comment by cannorin** [comment]
https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#--config-path-to-file-or-folder

**Comment by Krzysztof-Cieslak** [comment]
Reading config is done on the FSAC side.

**Comment by cannorin** [comment]
So we don't have to modify the client, right?

**Comment by cannorin** [comment]
Actually no change was required (sorry for being late!)

**Comment by kumkee** [comment]
> https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#--config-path-to-file-or-folder

The link is broken.
I don't know how to configure the integration and your documentation doesn't mention the details either. Please reopen this issue.

**Comment by cannorin** [comment]
@kumkee Please see here: https://fsprojects.github.io/fantomas/docs/index.html

Once you have installed and configured Fantomas, FSAC should use Fantomas as the formatter.

(Currently, #66 is affecting Ionide-vim and it won't work with the latest FSAC, so please allow me to take some time to get everything ready to work for you.)

**Comment by kumkee** [comment]
> (Currently, #66 is affecting Ionide-vim and it won't work with the latest FSAC, so please allow me to take some time to get everything ready to work for you.)

Then which is the latest version of FSAC that works with Ionide-vim?

Thank you, @cannorin.

**Comment by cannorin** [comment]
@kumkee v0.58.0 is working for me. v0.58.{1,2,3,4} might also work, but I haven't tested.

**Comment by kumkee** [comment]
> @kumkee v0.58.0 is working for me. v0.58.{1,2,3,4} might also work, but I haven't tested.

What version of fantomas are you using? I've tried FSAC v0.58.0 with fantomas v 5.1.5. Formatting doesn't work.
For your information, my nvchad [config](https://github.com/kumkee/nvchad_config) for formatting keys is `<space> + fm`.

**Comment by kumkee** [comment]
> If you don't see any kind of LSP-related error message, there is a good chance that the format command is not called at all.

What if the same key combo works in all other languages?

**Comment by cannorin** [comment]
It seems that you are using null-ls for formatting and it doesn't contain Fantomas?

https://github.com/kumkee/nvchad_config/blob/main/configs/null-ls.lua#L7C24-L34

**Comment by kumkee** [comment]
> It seems that you are using null-ls for formatting and it doesn't contain Fantomas?
> 
> https://github.com/kumkee/nvchad_config/blob/main/configs/null-ls.lua#L7C24-L34

It's funny that you asked. I've opened a [feature request issue](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1489) in null-ls. No one has responded. Please have a look.

**Comment by cannorin** [comment]
Since Ionide-vim delegates all the LSP functionalities (including formatting) to FSAC (and thus Fantomas), I guess Ionide-vim cannot help you solving the problem.

I think you can either
1. configure `nvim-lspconfig` to call the format command (as in https://github.com/neovim/nvim-lspconfig#suggested-configuration), or
2. try to make null-ls work with Fantomas.
