### ISSUE TITLE
FSI cannot be opened if is called after Vim no-file start (Windows x64)

### ISSUE THREAD

**Issue by cpkio** [ionide/Ionide-vim#17]
Installed language client and Vim_Fsharp yesterday, so vesions are up-to-date.

**Problem Description**
When Vim is started without a file (`vim.exe`), and `.fs` is loaded via `:e` command, FSI cannot be called (with **\<leader\>e**) with error message of
```
Error detected while processing function fsharp#toggleFsi:
line 7:                                                
E444: Cannot close last window                            
```
If Vim is started with a file name (`vim somefile.fs`), FSI opens normally. This affects both Vim and GVim.

`:FsiShow` command doesnt work anyway with `E119: Not enough arguments for function: fsharp#openFsi` error.

This has been tested with a blank Vim8.1 Windows installation with only LANGUAGECLIENT-NEOVIM and VIM_FSHARP_LANGUAGECLIENT installed.

**To Reproduce**
Steps to reproduce the behaviour:
1. start vim from the command line with no file option
2. load a file via `:e`
3. try to open an FSI console with **\<leader\>e** and get a
```
Error detected while processing function fsharp#toggleFsi:
line 7:                                                
E444: Cannot close last window                            
```
4. try to run `:FsiShow` command and get `E119: Not enough arguments for function: fsharp#openFsi` error.
5. Start `vim file.fs` and see **\<leader\>e** working fine. `:FsiShow` wont work anyway.

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Vim / Neovim version: 8.1x64 (2018 May 18)
 - dotnet SDK version: 3.0.100

**Comment by cannorin** [comment]
Reproduced in my environment.

**Comment by cpkio** [comment]
This commit didnt fix it for me, everything's the same.

**Comment by cannorin** [comment]
Make sure you updated the plugin correctly, as `FsiShow` will at least give you a different error.

**Comment by cpkio** [comment]
I have to apologize. This happened because of Pathogen package «manager», which somehow messed with Ionide. Everything's fine now.

**Comment by cannorin** [comment]
Great to hear that it's now working correctly. Thanks for reporting :pray:
