### ISSUE TITLE
Does this still work with vim8?

### ISSUE THREAD

**Issue by aVikingTrex** [ionide/Ionide-vim#19]
Still in my first week or two of using vim so it may just be me not understanding something. But the only feature that apparently is working for me is the syntax highlighting. Auto completions where not working until I installed deoplete (maybe i did need to do that?) but error highlighting ect does not work.
I have installed ionide and languageclient-neovim. I have python3 installed on my computer and have got both pynvim and neovim installed via pip3
Does anyone know what i have either done wrong here or if perhaps ive missed an installation step?
I have vim8.1 intalled via pacman in arch linux if this helps?

Below is my .vimrc file
``` 
filetype plugin on
call plug#begin()
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

Plug 'junegunn/fzf'

Plug 'ionide/Ionide-vim', {
      \ 'do':  'make fsautocomplete; read',
      \}
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && npm i' }
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
   Plug 'roxma/vim-hug-neovim-rpc' 
   Plug 'roxma/nvim-yarp' 
   Plug 'Shougo/deoplete.nvim'
endif
"Plug 'vim-syntastic/syntastic'
let g:deoplete#enable_at_startup=1
call plug#end()
set laststatus=2
set tabstop=4 softtabstop=4 noexpandtab
set hidden
set number 
nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>

let g:fsharp#show_signature_on_cursor_move = 1
let g:LanguageClient_serverCommands = {
	\ 'fsharp': g:fsharp#languageserver_command
	\ }

```

**Comment by cannorin** [comment]
When I tried several weeks ago, the Vim installation worked properly. Also, from the info you provided I believe you installed the plugin correctly. So what I suspected is the problem has something to do with the thing you are trying to open.

Did it show something like `Workspace Loaded` after opening a F# file?

**Comment by cannorin** [comment]
btw if you are new to Vim I'd recommend to use Neovim as it has more stability and advanced features, and less complexity to use.

**Comment by Bjorn-Strom** [comment]
I am having the same problems with Neovim.
Syntax Highlighting works but thats about it.

Followed the installation guide of Lanugage server and Ionide-vim.
Config file looks very similar to aVikingTrex's.

**Comment by aVikingTrex** [comment]
I actually went ahead and installed Neovim last night and ended up with the same result sadly. Bjorn appears to have experienced the same.

**Comment by cannorin** [comment]
Can you give me a zip of the project you are trying to open in order to replicate it by myself?

**Comment by Bjorn-Strom** [comment]
I just created a basic F# project from the terminal.
`dotnet new console --lang F# -o VimTest`

**Comment by aVikingTrex** [comment]
Further to what Bjorn did, I cant even get this to work outside of syntax highlighting for standalone .fsx files either

**Comment by cannorin** [comment]
That may be a separate problem so let's stick to the normal fsproj for now.
Did the plugin show something like `Workspace Loaded` after opening a F# file?

**Comment by Bjorn-Strom** [comment]
I am not a very experienced vim user. Where should this be output?

**Comment by cannorin** [comment]
It should be displayed in the status line (just below the editor).

**Comment by Bjorn-Strom** [comment]
Possible information overload here as I am just trying everything, but:
In the project directory i  type `nvim` and it displays nothing.
If I open the `.fsproj` file directly it flashes with `loading snippets`.
If I open the `.fs` file it flashes `loading snippets` and says `[LC] Project root: /Users/me/VimTest`

**Comment by cannorin** [comment]
Currently the plugin only works when you open single `.fs` file at startup and it is a limitation to be resolved later (tm).

In your case, I suspect that the plugin is not actually installed (while your vimrc is correctly configured). Can you try opening a `.fs` file and executing `:PlugInstall`?

**Comment by cannorin** [comment]
btw `g:fsharp#languageserver_command` is now deprecated and you can safely/should remove the

```
let g:LanguageClient_serverCommands = {
	\ 'fsharp': g:fsharp#languageserver_command
	\ }
```

part from your vimrc.

**Comment by Bjorn-Strom** [comment]
I removed the language client code and ran `:PlugInstall` on a newly created .fs file. Says `Ionide-vim` is already installed.

**Comment by cannorin** [comment]
Hmm, strange... Unfortunately I'll be busy for next few days (exam week) and I don't have enough time to look deep into this now. Meanwhile, can you use Ionide-VSCode with VSCodeVim plugin?

**Comment by Bjorn-Strom** [comment]
It's not an emergency for me, using VSCode now.
Have a good exam!

**Comment by benmp** [comment]
@aVikingTrex, @Bjorn-Strom 

Can you checkout pull #20 to see if that would fix your issue?

**Comment by Bjorn-Strom** [comment]
@benmp sorry for the late reply.
I tried #20 and it works! Really nice, thank you

**Comment by cannorin** [comment]
@benmp nice! I'll merge the PR.
@aVikingTrex Can you also check if #20 works for you? Unfortunately I don't have a time to try it myself yet.

**Comment by aVikingTrex** [comment]
Thank you so much @cannorin, that appears to all be working now. You are a legend!
