### ISSUE TITLE
Underline warnings/errors

### ISSUE THREAD

**Issue by benmp** [ionide/Ionide-vim#21]
When I use ionide-vscode, I can see warnings like:

<img width="1169" alt="Screen Shot 2019-11-22 at 3 08 01 PM" src="https://user-images.githubusercontent.com/9081154/69463803-ed138d80-0d39-11ea-8ba2-3e2514f7b08b.png">

When I use ionide-vim, I see:

![Screen Shot 2019-11-22 at 3 05 26 PM](https://user-images.githubusercontent.com/9081154/69463753-c48b9380-0d39-11ea-932f-c80c9c0794b8.png)

If this happens due to LanguageClient-neovim or colorscheme configuration, please ignore.

Otherwise, it would be cool to underline where in a given line of code the warning/error is referring to.

A 2nd bonus feature would be to enable moving the diagnostic message (seen in purple on vim) into the hover popup like vscode does.

Thanks!

**Comment by cannorin** [comment]
Sorry but it is handled by LC-Neovim. When #18 comes into reality we'll be able to have an underline at least.
