### ISSUE TITLE
Can't include more than one ProjectReference

### ISSUE THREAD

**Issue by PhilT** [ionide/Ionide-vim#23]
Maybe I'm doing something wrong but this [repo](https://github.com/PhilT/multiproj-fsharp) builds fine with `dotnet build` but when in Neovim I get `The namespace 'Dep2' is not defined`, despite having included it in the project. `Dep1` can be opened but not `Dep2`. I get the same issue when including `Dep2` in `Dep1` and then trying to reference `Dep2` in `main`.

![Screenshot 2020-03-27 11 38 29](https://user-images.githubusercontent.com/34678/77752523-9c7dab00-701f-11ea-8194-fbc6f3793dd3.png)

Main project file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dep1\dep1.fsproj" />
    <ProjectReference Include="..\dep2\dep2.fsproj" />
  </ItemGroup>

</Project>
```

I'm seeing the same issue with fsharp-language-server so maybe this issue belongs further upstream.

**Environment:**
 - OS: Windows 10
 - Vim / Neovim version: Neovim 0.4.3
 - dotnet SDK version: Core 3.1
 - mono / .Net Framework version:

**Comment by cannorin** [comment]
This seems to be rather a problem of FSAC. Known workaround is to create a solution file including all the projects.

**Comment by PhilT** [comment]
That project does indeed have a solution file which includes all the projects.

**Comment by PhilT** [comment]
I think maybe it's even further up than FSAC as it's happening in https://github.com/fsprojects/fsharp-language-server as well.

**Comment by cannorin** [comment]
First try `dotnet clean` and `dotnet build` as your project might be broken in the first place. Next, Ionide-vim shows a message like `[FSAC] Workspace loaded: <filename>`. Ensure that the `<filename>` points to a sln but not a fsproj. If it does not work, try setting `let g:fsharp#automatic_workspace_init = 0` in your vimrc and run `:FSharpParseProject` manually.

**Comment by PhilT** [comment]
Thank you for this. I've done as suggested. Here is what I get. 

`:FSharpParseProject` returns `[FSAC] Workspace loaded:` but no filename.

`:FSharpLoadWorkspaceAuto` returns `[FSAC] Workspace loaded: C:\...\matter\src\builder\tests\builder_tests.fsproj`. However, no errors or warnings appear if I first call `:FSharpParseProject`. If I just load Neovim and run `:FSharpLoadWorkspaceAuto` it loads from the project file and I do get the correct errors/warnings.

If I then try to open a file in a different project I get errors everywhere including a `problem reading assembly ucrtbase.dll`

If I put a dummy `.fs` file into the root and open it then sometimes I'll get `[FSAC] Workspace loaded: C:\...\matter\matter.sln`, however, opening any file I get the same errors all over the place including the assembly error.

![Screenshot 2020-03-28 16 15 03](https://user-images.githubusercontent.com/34678/77827810-b1396c00-710f-11ea-8b01-24d4f838c52e.png)

**Comment by cannorin** [comment]
ah I should have written it as `:FSharpParseProject <sln>`, my bad. this tells FSAC to explicitly load a solution and is supposed to work.
 
`ucrtbase.dll` seems to be something related to C runtime on Windows and not a .NET assembly. I'm not very sure what is going on under that error (the .NET Core SDK might be broken? but dotnet build is working in your case...)

**Comment by PhilT** [comment]
`:FSharpParseProject matter.sln` says it loaded the solution but I still don't get warnings/errors appearing.

**Comment by cannorin** [comment]
I tried with your repo and it works fine on my Linux laptop with the latest FSAC. This suggests the problem has something to do with your environment (likely Windows).

**Comment by cannorin** [comment]
Also this does not seem to be a problem of Ionide-vim.

**Comment by cannorin** [comment]
I suggest you to try it with Ionide-VSCode (which should be essentially the same besides the frontend). If it is also broken for you, re-open an issue in the FSAC repo. I'll try to reproduce it on my Windows PC (which is not available for next few days).
