### ISSUE TITLE
neovim LSP

### ISSUE THREAD

**Issue by Parasrah** [ionide/Ionide-vim#24]
**Is your feature request related to a problem? Please describe.**
The existing language client being used seems to be having issues with this plugin per #22 and #5 

**Describe the solution you'd like**
If using neovim `>=0.5.0` leverage the built in language client implementation (which is supported by the core neovim team and should be more stable) will be used for language server features. Otherwise, fallback to the existing language client.

**Describe alternatives you've considered**
`coc.nvim` was considered as an alternative, and has the benefit of working in vim 8 as well

**Additional context**
I will actually be the one working on this, just wanted to create an issue to keep the community updated as I work until I have a PR ready. If you'd rather use a PR for this kind of thing @cannorin, I'm happy to oblige

**Comment by cannorin** [comment]
Actually I was going to do this myself but didn't have enough free time. So if you can work on this it will help us a lot!

**Comment by Parasrah** [comment]
I'll do my best to make some time for it, although this is my first vim/lsp related contribution ever so we'll see if I manage to figure it out. I mostly spent yesterday trying to learn how the current code base works, and getting the neovim LSP setup with the default Rust config. 

At any point if I'm taking too long feel free to take it over, I'll completely understand

**Comment by Parasrah** [comment]
@cannorin I've been exploring this a bit more over the last couple of days and have some thoughts

I don't know that the built-in neovim language client is quite ready to use yet. I've been playing around with it in Rust, and it seems less reliable than the alternatives (`LanguageClient-neovim`, `coc.nvim`, etc). This makes sense as it's currently just on the development branch of neovim, and I'm sure it will get there at some point. There's also the worry that the current API has not stabilized. 

Additionally, I didn't realize that the `FsAutocomplete` project this plugin leverages actually adheres to the Language Server Protocol.

Given these things, it might make more sense in the long run to continue providing a built-in configuration leveraging the `LanguageClient-neovim` project, but add options to disable the LSP features and the linting features. Then, people that want to use an alternative LSP client are free to do so, and when [this](https://github.com/dense-analysis/ale/pull/2915) gets into `ale` people would be free to leverage ale for the linting experience as well. And they'd still be able to leverage the other features of this plugin such as the interactive repl. And you wouldn't have to support a bunch of different language clients, but could still provide a seamless experience people getting started

In the short term I'd like to try getting FsAutocomplete working with the nvim lsp (independent of this plugin) and make a PR to [nvim-lsp](https://github.com/neovim/nvim-lsp) with a basic config.

What do you think?

**Comment by cannorin** [comment]
@Parasrah Sounds good 👍

**Comment by Parasrah** [comment]
I was hoping to make a PR disabling the LSP/linting but I haven't had much time of late, and it doesn't help that I'm not actively writing any F# anymore. Since I'm not actively working on it I'll close this issue and someone else can open if they want to see that functionality and take it over
