### ISSUE TITLE
Paket.bootstrapper.exe won't run and needs updating

### ISSUE THREAD

**Issue by PhilT** [ionide/Ionide-vim#26]
Unable to communicate with GitHub. See: https://github.com/fsprojects/Paket/issues/3065

**Comment by cannorin** [comment]
I think today we can easily install FAKE through .NET Core so there is no need to use paket any more. Is it okay just to remove it and upgrade the fsx to the latest FAKE?

**Comment by PhilT** [comment]
Seems reasonable to me.
