### ISSUE TITLE
Send `;;` on new line to avoid problems with line comments

### ISSUE THREAD

**Issue by entropitor** [ionide/Ionide-vim#32]
**Is your feature request related to a problem? Please describe.**
When using `alt+enter` on a line with a line comment at the end, the code is not actually evaluated

**Describe the solution you'd like**
sent the line, `\n` (to terminate the line comment) and only then `;;`

**Describe alternatives you've considered**
- The developer has to manually enter `;;` in the repl / visually select until the line comment
- Don't sent the line comment to the repl

**Additional context**
Example line that has the problem:
```fsharp
Some 1 |> Option.get // An example comment
```

**Comment by cannorin** [comment]
This will be a small modification to https://github.com/ionide/Ionide-vim/blob/master/autoload/fsharp.vim#L462-L473 . I can't do that right now (maybe tomorrow) so feel free to PR!
