### ISSUE TITLE
Getting 'E117: Unknown function: LanguageClient#HasCommand' when opening fs files

### ISSUE THREAD

**Issue by lucabol** [ionide/Ionide-vim#34]
FULL ERROR TEXT
Error detected while processing function <SNR>40_OnBufEnter:
line    1:
E117: Unknown function: LanguageClient#HasCommand
E15: Invalid expression: !LanguageClient#HasCommand(&filetype)
line    5:
E117: Unknown function: LanguageClient#handleBufEnter

[deoplete] Duplicated source: LanguageClient.  Use :messages / see above for error d
etails.

LOG FOR LANGUAGE SERVER
Invalid runtimeconfig.json [/home/lucabol/.config/nvim/plugged/Ionide-vim/fsac/f    sautocomplete.runtimeconfig.json] [/home/lucabol/.config/nvim/plugged/Ionide-vim    /fsac/fsautocomplete.runtimeconfig.dev.json]

SYSTEM
Linux Arch with the followgin packages
languageclient-neovim-bin 0.1.161-1
neovim 0.4.4-1

INIT.VIM
call plug#begin("$XDG_CONFIG_HOME/nvim/plugged")
    Plug 'chrisbra/csv.vim'
    Plug 'moll/vim-bbye'
    Plug 'simeji/winresizer'
    Plug 'simnalamburt/vim-mundo'
    Plug 'autozimu/LanguageClient-neovim', {
        \ 'branch': 'next',
        \ 'tag': '0.1.155',
        \ 'do': 'bash install.sh',
        \ }
    Plug 'ionide/Ionide-vim', {
          \ 'do':  'make fsautocomplete',
          \}
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    Plug 'junegunn/fzf.vim'
call plug#end()

let g:deoplete#enable_at_startup = 1

augroup filetype_fsharp
    autocmd!
    autocmd BufReadPost *.fs setlocal filetype=fsharp
    autocmd BufReadPost *.fsx setlocal filetype=fsharp
augroup END

let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_virtualTextPrefix = ''
let g:LanguageClient_loggingFile =  expand('~/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')

" Autosave
au TextChanged,TextChangedI <buffer> if &readonly == 0 && filereadable(bufname('%')) | silent write | endif

set clipboard+=unnamedplus

map <Space> <Leader>

noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

nnoremap <c-w>h <c-w>s

nmap <Leader><space> :! urxvtc -e bash -i -c "nvim %"<enter><enter>

set noswapfile

" save undo trees in files
set undofile
set undodir=$HOME/.config/nvim/undo

" number of undo saved
set undolevels=10000
set undoreload=10000

set number

" use 4 spaces instead of tab ()
" copy indent from current line when starting a new line

set autoindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Show substitution
set inccommand=nosplit

set hidden

augroup filetype_csv
    autocmd!
    autocmd BufRead,BufWritePost *.csv :%ArrangeColumn!
    autocmd BufWritePre *.csv :%UnArrangeColumn
augroup END

let g:winresizer_start_key = "<leade>w"

" Enable persistent undo so that undo history persists across vim sessions
set undofile
set undodir=~/.vim/undor

**Comment by cannorin** [comment]
@lucabol can you test it out with the latest Ionide-vim? You would need to run `:PlugUpdate Ionide-vim` and [`:FSharpUpdateFSAC`](https://github.com/ionide/Ionide-vim#fsharpupdatefsac).

**Comment by lucabol** [comment]
Same error. I cannot run :FSharpUpdateFSAC because it is not an editor command.

:PlugUpdate Ionide-vim seems to work.

**Comment by lucabol** [comment]
Here is what I am getting:

Error detected while processing function <SNR>35_OnBufEnter:
line    1:
E117: Unknown function: LanguageClient#HasCommand
E15: Invalid expression: !LanguageClient#HasCommand(&filetype)
line    5:
E117: Unknown function: LanguageClient#handleBufEnter

And here is my init.vim

call plug#begin("$XDG_CONFIG_HOME/nvim/plugged")
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'tag': '0.1.155',
    \ 'do': 'bash install.sh',
    \ }
Plug 'ionide/Ionide-vim', {
    \ 'do': 'make fsautocomplete',
    \}
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:deoplete#enable_at_startup = 1

augroup filetype_fsharp
autocmd!
autocmd BufReadPost *.fs setlocal filetype=fsharp
autocmd BufReadPost *.fsx setlocal filetype=fsharp
augroup END

let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_virtualTextPrefix = ''
let g:LanguageClient_loggingFile = expand('/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('/.local/share/nvim/LanguageServer.log')

" Autosave
au TextChanged,TextChangedI if &readonly == 0 && filereadable(bufname('%')) | silent write | endif

set clipboard+=unnamedplus

nnoremap h s

nmap :! urxvtc -e bash -i -c "nvim %"

set noswapfile

" save undo trees in files
set undofile
set undodir=$HOME/.config/nvim/undo

" number of undo saved
set undolevels=10000
set undoreload=10000

set number

" use 4 spaces instead of tab ()
" copy indent from current line when starting a new line

set autoindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Show substitution
set inccommand=nosplit

set hidden

augroup filetype_csv
autocmd!
autocmd BufRead,BufWritePost *.csv :%ArrangeColumn!
autocmd BufWritePre *.csv :%UnArrangeColumn
augroup END

let g:winresizer_start_key = "w"

" Enable persistent undo so that undo history persists across vim sessions
set undofile
set undodir=~/.vim/undor

**Comment by cannorin** [comment]
Ionide-vim now uses nvim's built-in LSP client, which makes `autozimu/LanguageClient-neovim` unnecessary. This issue seems to be caused because LC-neovim is somehow failing to load, so I think it is now invalid and can be closed.
