### ISSUE TITLE
Code lens in NeoVim

### ISSUE THREAD

**Issue by zetashift** [ionide/Ionide-vim#36]
Code lense just landed in neovim https://github.com/neovim/neovim/pull/13165 
Any chance we can hook this up to ionide-vim?

**Comment by cannorin** [comment]
yeah I love to have code lens supported, I'll work on this

**Comment by cannorin** [comment]
It turns out LanguageClient-neovim has been supporting code lens since before.

I fixed the default configuration passed to FSAC so you should see code lenses out of the box.

**Comment by cannorin** [comment]
You might notice the type signature is not displayed at all. See https://github.com/fsharp/FsAutoComplete/issues/808 about this.
