### ISSUE TITLE
Ionide fails to attach the second time it is requested (using NeoVim's built-in LSP server)

### ISSUE THREAD

**Issue by OmanF** [ionide/Ionide-vim#39]
**Describe the bug**
When starting an F# file for a second (third...) time, either by opening a new file, closing and re-opening the same file, etc., the `ionide` LSP client fails to start (or attach, I can't figure out if which of the two), as can be evidenced by running `LspInfo` on the buffer.

(Please see environment specs, and snippet from `init.vim` below).

**To Reproduce**
(See attached screencast)

1. Start NeoVim, configured with the built-in LSP server and `Ionide-vim` plugin
2. Start an F# file and wait for `Ionide` to kick in
3. Start another F# file

**Expected behaviour**
`Ionide` should attach to the second (third, so on) instances of an F# file

**Screenshots**

https://user-images.githubusercontent.com/7848797/131493371-736c89d3-53d9-419f-b2ef-358f0e1ee476.mp4

https://user-images.githubusercontent.com/7848797/131493449-6791f9e5-2485-432a-9841-2bb0e7b9a7f6.mp4

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 **running on WSL2!**
 - Vim / Neovim version: NeoVim 0.6.0-Dev (Nightly)
 - dotnet SDK version: 5.0.400
 - mono / .Net Framework version: N/A

**Additional context**
The relevant parts of my `init.vim`:

```
Plug 'ionide/Ionide-vim', { ' do': 'make fsautocomplete' }
Plug 'nvim-lua/plenary.nvim'
Plug 'neovim/nvim-lspconfig'
Plug 'kabouzeid/nvim-lspinstall'

lua << EOF
local function setup_servers()
    require('lspinstall').setup()
    local servers = require('lspinstall').installed_servers()
    for _, server in pairs(servers) do
        require('lspconfig')[server].setup{}
    end
end

require('lspinstall').post_install_hook = function ()
    setup_servers()
    vim.cmd("bufdo e")
end

setup_servers()
EOF
```

**Note**: `lsp-install` does **not**, yet, have an `fsautocomplete` installer, so I'm effectively following the instructions on the README about not hooking `Ionide-vim` to the LSP manually but instead letting it inject itself (which it does successfully, the first, and only first, time an F# file is opened).

**Comment by cannorin** [comment]
Can you try it with the https://github.com/ionide/Ionide-vim/tree/better-performance-and-syntax branch? The current `master` version can call the `setup` function multiple times, and I remember I encountered a similar problem because of that.

**Comment by cannorin** [comment]
Ah nevermind, the above one shoule be fixed in https://github.com/ionide/Ionide-vim/commit/74b2d3b9a887a887304db64dbcf4a8ecd7d63772 . I think this is a separate issue then.

**Comment by cannorin** [comment]
Can you check if https://github.com/ionide/Ionide-vim/tree/fix-39 fixes the problem?

**Comment by OmanF** [comment]
Can you walk me through this, please?
I cloned the repo, switched to the correct branch, and ran `make fsautocomplete`. I now have an `fsac` folder in the repo folder.

I know I have a corresponding `fsac` folder under `~/<user>/.config/nvim/data/plugged`.
Do I swap them manually? Do something else? Do I leave the `{'do': 'make fsautocomplete'}` on my `init.nvim`?

Sorry, I usually just do `Plug ...` and am happy. :D

**Comment by cannorin** [comment]
You can just do 
```
Plug 'ionide/Ionide-vim', {
     \ 'branch': 'fix-39',
     \ 'do':  'make fsautocomplete',
     \}
```
🙂

**Comment by OmanF** [comment]
Hi.
I'm sorry, but it looks like it makes things worse (see attached screencast).
Luckily reverting the change takes us back to the "original" state of this ticket, where the first F# file to be opened has `Ionide` attached.


https://user-images.githubusercontent.com/7848797/132087837-1551c0dc-a58e-4c37-acb5-90104920c1ab.mp4

**Comment by gsuuon** [comment]
FWIW I ran into this and the `fix-39` branch seems to have resolved it.

**Comment by OmanF** [comment]
I came back to this issue because I remembered another commenter said that the proposed fix worked for him.
I then tried the fix verbatim, i.e. using the line breaks and the `\...` notation (as you can see in a previous screencast, before I add the branch inline).

Now, I don't get why inlining options for Vim, versus, using line breaks makes a difference, but it does.
I can open as many F# files as I want, `Ionide` starts on all of them correctly and performs as expected.

Closing this issue and hoping it will be merged soon so I can drop the `branch` clause in my config. 😆 

Thanks for fixing it and keep up the great work!

**Comment by cannorin** [comment]
merged! ❤️
