### ISSUE TITLE
Wrap messages of compile error

### ISSUE THREAD

**Issue by kmyk** [ionide/Ionide-vim#4]
**Is your feature request related to a problem? Please describe.**
Long messages are truncated. This behavior is inconvenient.

![Screenshot from 2019-07-16 18-47-29](https://user-images.githubusercontent.com/2203128/61286832-a26b8d00-a7fe-11e9-95db-b7347790578e.png)

**Describe the solution you'd like**
Wrap the messages.

**Describe alternatives you've considered**
Display messages in the status line without truncation.

**Comment by cannorin** [comment]
This may be the matter of properly configuring LanguageClient-neovim rather than ours.

We might be better providing a default configuration that just works well out of the box, including this, key bindings, etc.

**Comment by cannorin** [comment]
It seems LC-vim can display errors and warnings in QuickFix window so you can just use `:cw`.
