### ISSUE TITLE
Function selection tooltip doesn't show the heredoc

### ISSUE THREAD

**Issue by OmanF** [ionide/Ionide-vim#41]
**Describe the bug**
When choosing an autocomplete function from the pop-up, the hovered over function's heredoc isn't displayed in the pop-up window, instead the window is blank

**To Reproduce**
Steps to reproduce the behaviour:
1. Invoke the autocomplete pop-up (for example, type `List.` and wait for the autocomplete pop-up to show all `List`'s module functions).
2. Iterate over the functions.

**Expected behaviour**
Each hovered over function should show its heredoc in the pop-up window.

**Screenshots**

https://user-images.githubusercontent.com/7848797/140601668-e0593a56-30ec-4c11-8a10-bd089d4fb5dd.mp4

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 on WSL2 on Windows 10.
 - Vim / Neovim version: 0.6.0-Dev (nightly)
 - dotnet SDK version: 5.0.402
 - mono / .Net Framework version: 5.0.402

**Comment by cannorin** [comment]
This is just deoplete + LC-neovim/nvim's LSP lacking such a feature. We need to find a way to invoke hover from deoplete. Also, users might be using a different autocompletion plugin than deoplete, which makes things more complicated.

**Comment by cannorin** [comment]
I've figured out this is because `deoplete-lsp` does not call `completionItem/resolve`.

**Comment by OmanF** [comment]
Great!
Thanks for your constant work on improving this plugin!

**Comment by cannorin** [comment]
Closing this in favor of #46 since this is because `deoplete-lsp` is lacking the required feature, and this would not be improved since its development is finished.
