### ISSUE TITLE
Post-update hook for Ionide-vim ... Exit status: 127

### ISSUE THREAD

**Issue by romanprocopie** [ionide/Ionide-vim#42]
Cannot get this working on latest ubuntu, tried latest vim and neovim from pkg repos, as well as nvim 0.5.1 from appimage

My init.vim looks like this

```
call plug#begin('~/.vim/plugged')
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'junegunn/fzf'
Plug 'ionide/Ionide-vim', {
      \ 'do':  'make fsautocomplete',
      \}
call plug#end()

```
Same thing happens when I just enable Ionide-vim without the others.
During :PlugInstall I get the msg from the title.

If I run nvim with no params after that, I get
```
Error detected while processing /home/rprocopie/.vim/plugged/Ionide-vim/plugin/ionide.vim:
line   11:
E5108: Error executing lua /home/rprocopie/.vim/plugged/Ionide-vim/lua/ionide/init.lua:111: attempt to concatenate local 'root_dir' (a nil value)

```
```
$ dotnet --list-sdks
3.1.414 [/usr/share/dotnet/sdk]
5.0.402 [/usr/share/dotnet/sdk]

```

**Comment by romanprocopie** [comment]
Similar thing on MacOs Big Sur, with Nvim 0.5.1 installed form brew. I don't get the error during installation, but running Nvim without args produces the same error.

Seems to load the file correctly if I specify it as a cmd line arg, the plugin commands seem to work, I am going through a bit of a learning curve now to be honest

**Comment by cannorin** [comment]
It was a bug introduced in https://github.com/ionide/Ionide-vim/commit/80620da7ef45f9799b73bb4dca238dbfff614145.

Before the commit, the automatic setup would run after a F# file is opened. But after the commit, it runs every time neovim is opened, causing the issue.

**Comment by romanprocopie** [comment]
> It was a bug introduced in [80620da](https://github.com/ionide/Ionide-vim/commit/80620da7ef45f9799b73bb4dca238dbfff614145).
> 
> Before the commit, the automatic setup would run after a F# file is opened. But after the commit, it runs every time neovim is opened, causing the issue.

So, pardon my ignorance, how do I actually get to install this on ubuntu, or what is the workaround ?

**Comment by cannorin** [comment]
@romanprocopie run `:PlugUpdate` () again, so that you can install the fixed version.

**Comment by cannorin** [comment]
@romanprocopie if it still doesn't work don't hesitate to ask me 🙂

**Comment by romanprocopie** [comment]
@cannorin that seems to have helped, many thanks
