### ISSUE TITLE
Recommends deoplete.nvim, which says "The development of this plugin is finished"

### ISSUE THREAD

**Issue by mhansen** [ionide/Ionide-vim#46]
Hey, just wondering if we should still recommned deoplete.nvim. On their README they say:

> The development of this plugin is finished. Accepts minor patches and issues but no new features. [ddc.vim](https://github.com/Shougo/ddc.vim) is the next generation auto completion plugin. Consider migrating to it.

Should this project recommend ddc?

**Comment by cannorin** [comment]
I think it may be better to migrate to other plugin, but I don't think ddc.vim would be an option.

> If you don't want to configure plugins, you don't have to use the plugin. It does not work with zero configuration. You can use other plugins.

ddc.vim is clearly for advanced Vim users, so I don't think it would be good for a default completion plugins.

Ionide-vim does not depend on a specific completion plugin, so users are able to use ddc.vim anyway if they want.

**Comment by cannorin** [comment]
I'm recently testing https://github.com/hrsh7th/nvim-cmp personally for #41 .

**Comment by zetashift** [comment]
+1 for `nvim-cmp` I use it too and it's nice!

**Comment by cannorin** [comment]
deoplete also lacks the heredoc feature on completion, which is another reason to migrate to nvim-cmp.

**Comment by cannorin** [comment]
I've written an example `.vimrc` to use nvim-cmp: https://github.com/ionide/Ionide-vim/wiki/Configuration-Examples#with-nvim-lspconfig-and-nvim-cmp-for-neovim-05

**Comment by cannorin** [comment]
We now officially recommend nvim-cmp, but since it is a bit complicated to setup (while deoplete takes only a few lines), I leave the deoplete example as a reference.
