### ISSUE TITLE
Option to make completion case-insensitive?

### ISSUE THREAD

**Issue by tnishimura** [ionide/Ionide-vim#49]
**Is your feature request related to a problem? Please describe.**
Completion is currently case-sensitive. I.e., when I type "l" the completion menu offers 'log', 'log10', 'let', etc. but not 'List', 'Linq', etc.

**Describe the solution you'd like**
Offer an option to make ionide-vim behave like omnisharp-vim for C#, where completions are case insensitive. 

**Describe alternatives you've considered**
N/A

**Additional context**
I'm using the Vim 8.2 with ionide-vim (latest git version), LanguageClient-neovim (latest git version), and fsac 0.50.0. Using omnicomplete (C-x C-o) for 'launching' completion, through supertab, if that matters.  Honestly I'm not sure which of these projects would be involved in enabling case-insensitive completions. I've tried "vim-level" settings like `set ignorecase` and `set infercase` but they do nothing. I've search the repos for the other projects for keywords like 'sensitivity' and 'case' but have not found anything relevant.

**Comment by cannorin** [comment]
This would be an enhancement to FSAC itself. Please open an issue on https://github.com/fsharp/FsAutoComplete.

**Comment by tnishimura** [comment]
Done: https://github.com/fsharp/FsAutoComplete/issues/886
