### ISSUE TITLE
Filetype not automatically set to F#

### ISSUE THREAD

**Issue by zetashift** [ionide/Ionide-vim#50]
**Describe the bug**
Currently when I open any F# related file(fs, fsx, fsproj), I don't get anything from the plugin because the filetype is being recognized as Forth.

**To Reproduce**
Steps to reproduce the behaviour:
Not sure, since the docs don't mention anything about this and I think the plugin does it automatically?

**Expected behaviour**
Filetypes fs, fsx being recognized as F#.

**Screenshots**
![image](https://user-images.githubusercontent.com/1857826/152616295-5ef6d4af-c385-496c-83d2-912b92d16a15.png)

**Environment (please complete the following information):**
 - OS: Linux 
 - Vim / Neovim version: NVIM v0.7.0-dev
 - dotnet SDK version: 6

**Additional context**
I can probably fix this by setting an autocommand

**Comment by tnishimura** [comment]
Are you sure you have ionide-vim installed correctly? `ftdetect/fsharp.vim` definitely should be doing the job: 
```
autocmd BufNewFile,BufRead *.fs,*.fsi,*.fsx set filetype=fsharp
autocmd BufNewFile,BufRead *.fsproj         set filetype=fsharp_project
```
You could put that in your vimrc but you shouldn't have to...

**Comment by cannorin** [comment]
This should never happen as @tnishimura explained. We would need to look at your vimrc to see what is going on?

**Comment by zetashift** [comment]
So packer, the plugin manager I use for neovim, didn't copy the Ionide-vim files correctly, reinstalling Ionide-vim worked, but I had done that several times before. Sorry for bothering, but reinstalling worked!
