### ISSUE TITLE
ionide complaining of no symbol when .. there shouldn't be one.. 

### ISSUE THREAD

**Issue by WillEhrendreich** [ionide/Ionide-vim#58]
When I move the cursor in neovim, I get an error that constantly tells me I don't have symbol information.. 

![image](https://user-images.githubusercontent.com/55286472/179075706-87c02288-2b7c-4c49-b133-1744d84051c4.png)

**To Reproduce**
Move the cursor over anything that isnt a word.. like blank spaces. 

**Expected behaviour**
That it would stop informing me that it's not finding them.. 

**Environment (please complete the following information):**
 - OS: Windows 
 - Vim / Neovim version: 0.7.2
 - dotnet SDK version: 6
 - mono / .Net Framework version: nope. 

**Additional context**
I'm using [Astronvim](https://github.com/AstroNvim/AstroNvim) as my base config. it uses LspInstaller, and lspconfig. I'm using no special config past that.

**Comment by cannorin** [comment]
Symbol information is not the default feature of Ionide-vim, and you must have to write some settings to enable it.

If you have something like
```vim
if has('nvim') && exists('*nvim_open_win')
  augroup FSharpShowTooltip
    autocmd!
    autocmd CursorHold *.fs,*.fsi,*.fsx call fsharp#showTooltip()
  augroup END
endif
```
in your vimrc, please remove it. It seems it doesn't work well with AstroNvim.

But I suspect that's not the case. Does AstroNvim send the symbol information requests every time you move the cursor? It's kind of natural that FsAutoComplete (F# LSP server) returns an error if you request a symbol info of empty space, so I suspect that it's rather AstroNvim's problem.

**Comment by cannorin** [comment]
It looks like what I said is wrong. Reopened and I'm investigating.

**Comment by cannorin** [comment]
The correct setting was `fsharp#show_signature_on_cursor_move`, and it was *enabled* by default.

Can you do
```vim
let g:fsharp#show_signature_on_cursor_move = 0
```
? The error messages should go away with this.

**Comment by cannorin** [comment]
This feature is now disabled by default.
