### ISSUE TITLE
Comment lines affect indentation

### ISSUE THREAD

**Issue by usualwitch** [ionide/Ionide-vim#67]
**Describe the bug**
If a comment line ends with one of the patterns defined in https://github.com/ionide/Ionide-vim/blob/master/indent/fsharp.vim#L189, the next line will be indented.

**To Reproduce**
Write a comment that ends with any word from this list `begin\|do\|else\|fun\|function\|functor\|if\|initializer\|object\|private\|sig\|struct\|then\|try` then press enter. The next line will be shifted right.

**Expected behaviour**
Comment lines should not change indentation.

**Comment by cannorin** [comment]
@usualwitch Note that #71 is not perfect: it will still increase indentation within ranged comments `(* ... *)` since there is apparently no efficient way for Vim's indent file to know if the current position is within ranged comment.

It will fix the following case, though:
```fsharp
// begin
// something
```
