### ISSUE TITLE
CodeLens doesn't always refresh

### ISSUE THREAD

**Issue by no1melman** [ionide/Ionide-vim#69]
**Describe the bug**
Essentially, after opening a couple of buffers, CodeLens stops loading properly

**To Reproduce**
Steps to reproduce the behaviour:

I have NvChad, so a tree explorer, and nvim lsp with Ionide loaded

1. Open up several buffers
2. See the codelens start to fail

**Expected behaviour**
CodeLens should always show...

**Screenshots**
![image](https://github.com/ionide/Ionide-vim/assets/13630254/63e34b7f-18f5-4835-a2f8-b7ba5cb9d256)

**Environment (please complete the following information):**
 - OS: Windows
 - Neovim version: 0.9.1
 - dotnet SDK version: 7.0.304

**Additional context**
I have created a command to automagically call this for me

```lua
vim.api.nvim_create_user_command("FSharpRefreshCodeLens", function()
  vim.lsp.codelens.refresh()
  print "working..."
end, {
  bang = true,
})
```

In my init.lua script, if anyone was curious on how to get around this...

**Comment by cannorin** [comment]
@no1melman Hi! Can you check (with the workaround removed) if the [fix-69](https://github.com/ionide/Ionide-vim/tree/fix-69) branch fixes the problem? It injects `vim.lsp.codelens.refresh()` to `on_attach`.

**Comment by no1melman** [comment]
OOOOoooo I will have a check in a bit
