### ISSUE TITLE
show_signature_on_cursor_move doesn't seem to work on fresh install

### ISSUE THREAD

**Issue by boek** [ionide/Ionide-vim#7]
**Describe the bug**
When I first installed the vim plugin I got the signature on the statusline. On a fresh install on both macOS and Ubuntu 19.04 I can't seem to enable this behavior anymore. I'm pretty sure I'm just missing something, but I'm not sure how to debug what that is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow installation instructions (Tried in vim and neovim)
2. Load a dotnet core project
3. Get the statusline message saying the fsproj was loaded
4. Move cursor over a let or function

**Expected behaviour**
I get the type signature on the statusline

**Environment (please complete the following information):**
 - OS: Ubuntu 19.04
 - Ionide version: master
- Vim 8.1 and NeoVim 0.4 and 0.5
 - dotnet SDK version: 2.3 and 3.0.100-preview9-014004
 - mono / .Net Framework version: n/a

---

Other features like the gutter showing errors does work though! So I know the plugin is working :)

**Comment by cannorin** [comment]
I'll try to reproduce this. Let me know whether it also happens on newly created projects (preferably with `dotnet new console -lang F#`).

**Comment by boek** [comment]
@cannorin Yes, I've only tested on newly created projects. Let me know if there is any other info you need!

**Comment by boek** [comment]
Update: :upside_down_face: it randomly started working again. No idea why..

**Comment by cannorin** [comment]
I failed to reproduce it. Maybe it was the problem of FSAC rather than Ionide-vim?
