### ISSUE TITLE
Unable to get any autocomplete when opening fsx files

### ISSUE THREAD

**Issue by grab-a-byte** [ionide/Ionide-vim#75]
**Describe the bug**
I have followed the guide and installed fsautocomplete globally and also installed the plugin. My init.vim file looks like the following. 
 ```
call plug#begin()
Plug 'ThePrimeagen/vim-be-good'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'deoplete-plugins/deoplete-lsp'
Plug 'ionide/Ionide-vim'
Plug 'vim-airline/vim-airline'
call plug#end()

set number
set relativenumber
```

**To Reproduce**
Steps to reproduce the behaviour:
1) Fresh install of neovim.
2)  run `dotnet tool install -g fsautocomplete`
3) Add the above contents to the init.vim file (found in "C:\Users\USER\AppData\Local\nvim\init.vim" on windows)
4) open a fsx file and try and type something and get intellisence/autocomplete. 

**Expected behaviour**
Expect a popup with some sort of autocomplete suggestion.

**Screenshots**
![image](https://github.com/ionide/Ionide-vim/assets/30392071/b0deb30d-61c0-4747-8138-fe51f5ec62b5)
No Autocomplete suggestions at all

**Environment (please complete the following information):**
 - OS: Windows 11 22H2 - Build 22621.2134
 - Vim / Neovim version: Neovim v0.9.1
 - dotnet SDK version: 7.0.400-preview.23274.1
 - mono / .Net Framework version: N/A

**Additional context**
Apologies if I have missed something or not understood. I am new to Neovim and trying to learn it and though F# being my favorite language I don't get a chance to use, i'd use it to try and learn some Neovim for fun so apologies of the question is obvious and I've missed something very clear.

**Comment by cannorin** [comment]
I guess it is caused by either Ionide-vim not recognizing `fsx` as a workspace marker, or FSAC not supposed to work with a single `fsx` (I don't remember if it is really the case). 

For a workaround, creating an empty F# project in the same directory through `dotnet new console -lang:F# -o .` may help.

**Comment by baronfel** [comment]
FSAC does support loose loose fsx scripts (the compiler tooling interprets them as projects with a single source file and a standard set of project options).

**Comment by cannorin** [comment]
Yes, `.fsx` is associated to the `fsharp` filetype.

https://github.com/ionide/Ionide-vim/blob/master/ftdetect/fsharp.vim#L2-L3

So, my guess is that Ionide-vim is just failing to start FSAC if there are no `sln` or `fsproj`.

https://github.com/ionide/Ionide-vim/blob/master/lua/ionide/init.lua#L45-L47

https://github.com/ionide/Ionide-vim/blob/master/autoload/fsharp.vim#L298-L300

**Comment by grab-a-byte** [comment]
Hi there, I've tried it with a FsProj from dotnet new console as shown here 
![image](https://github.com/ionide/Ionide-vim/assets/30392071/81896920-b3da-4614-9c84-f77d67d3e4b4)

Still Not getting any suggestions as seen in this screenshot. 
![image](https://github.com/ionide/Ionide-vim/assets/30392071/7bd3296d-6298-471d-bc36-fb2fc18b76a3)


Does appear to be working a bit more however based on the fact that in normal mode I seem to be getting more information. 
![image](https://github.com/ionide/Ionide-vim/assets/30392071/bfc4eb44-693a-42ac-8f79-343d5255872c)

Any further suggestions?

**Comment by grab-a-byte** [comment]
Strangely enough doing this with VimPlug didnt seem to work but added via Mason with kickstart.nvim and it's workign now. Thanks for the suggestion. Any way i'd be able to make this work for standalone fsx files? Happy to close this for now however.

**Comment by niontrix** [comment]
Hi guys,
I know this is already closed, but I recently stumbled upon the same problem, that ionide is not activating a workspace and launching `fsac` when opening an `.fsx` file. I had a look at https://github.com/ionide/Ionide-vim/blob/master/lua/ionide/init.lua#L45-L47 and I think @cannorin is right. The rootMarkers list does not contain `fsx`. But if you simply create a git repository in the same folder it also works.
Maybe we could add `fsx` to the list explicitly, which would make for a better UX, imo.
Maybe I will create a PR.
