### ISSUE TITLE
FSharpLoadProject causes callback error

### ISSUE THREAD

**Issue by DashieTM** [ionide/Ionide-vim#87]
**Describe the bug**
After loading the project via FSharpLoadProject, the plugin throws an error trying to call a callback, which seems to not exist.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open an F# project with neovim.
2. Load a project with FSharpLoadProject test.sln
3. The project loads but returns the callback error

**Expected behaviour**
Callback to not be called if it isn't a function (likely fix)

**Screenshots**
![image](https://github.com/user-attachments/assets/0d39b0c0-33c1-4174-91e1-5e998dfdbed7)

**Environment (please complete the following information):**
 - OS: NixOS
 - Vim / Neovim version: NVIM v0.10.1 -> via NixVim 
 - dotnet SDK version: 8.0.303
 - mono / .Net Framework version: 8.0.7

Sidenote, awesome plugin though! Quite frankly, this plugin and specifically this command saved me from being forced to use rider. :) So massive thanks.

**Comment by cannorin** [comment]
I couldn't reproduce the issue but I think 268955c will prevent this kind of error. Please reopen it if it doesn't fix the problem for you. Thanks!
